# python
#
# VERSION               2.7.8

FROM images.docker.sohuno.com/redhat:7.0
MAINTAINER "XueMingZhang@sohu-inc.com"

COPY sce_docker.repo /etc/yum.repos.d/

RUN yum  -y install python-sce

RUN useradd app

RUN mkdir -p /opt/logs /opt/conf /opt/scripts /opt/src
COPY nginx /opt/scripts/nginx
COPY sce /opt/scripts/sce 
COPY start.sh /sbin/

EXPOSE      22

CMD ["/sbin/start.sh"]
