# php
#
# PHP VERSION               5.5.13

FROM images.docker.sohuno.com/nginx:1.6.0
#MAINTAINER "XueMingZhang@sohu-inc.com"

COPY php5.repo /etc/yum.repos.d/
RUN yum clean all && yum  -y install libmemcached php-5.5.13

ENV PHP_HOME=/opt/apps/php \
    PHP_VERSION=5.5.13 \
    PHP_FPM_START=/opt/scripts/sce/phpfpmrestart.sh \
    SERVER_START=/opt/scripts/sce/phpfpmrestart.sh

#COPY php/php.ini $PHP_HOME/lib/php.ini
COPY php/php-fpm.conf /opt/conf/php-fpm.conf
COPY php/phpfpmrestart.sh  /opt/scripts/sce/phpfpmrestart.sh

CMD ["/sbin/start.sh"]
