# jetty jdk
#
# VERSION               1.7.0

FROM images.docker.sohuno.com/nginx:1.6.0
MAINTAINER "XueMingZhang@sohu-inc.com"

RUN yum  -y install jdk jetty

ENV JAVA_HOME /opt/apps/jdk
ENV CLASSPATH ./:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar
ENV PATH $JAVA_HOME/bin:$PATH

EXPOSE      22 80

CMD ["/sbin/start.sh"]
